on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set timestamp
        id: timestamp
        run: echo "::set-output name=timestamp::$(date +%s)"

      - name: Build the Docker image
        run: docker build .devcontainer --file .devcontainer/Dockerfile --tag my-image-name:${{ steps.timestamp.outputs.timestamp }}

      - name: Log into Docker Hub
        run: docker login -u beehives2022 -p VEGAcore2016

     - name: Push the Docker image to Docker Hub
  run: docker push beehives2022/search:tagname:${{ steps.timestamp.outputs.timestamp }}

